name: Delete workflow run record
on:
# Run weekly, at 00:00 on sunday.
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for current repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.WORK_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3

      - name: Delete workflow runs for remote repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'FlameTech6/Zeep_Sport_Robot'
          retain_days: 7
          keep_minimum_runs: 6
